freebsd_instance:
  image_family: freebsd-12-0

task:
  prerequisites_script:
    - pkg install -y pkgconf vips libnghttp2 node npm
  install_script:
    - npm install --unsafe-perm
  test_script:
    - npm test
